# bind to this address to accept new TLS connections
bind_addr: "[2409:12:6320:5000:215:17ff:feea:44cc]:443"

frontends:
  fono.jp:
    backends:
      -
        addr: "[::1]:8443"
  vpn.fono.jp:
    backends:
      -
        addr: "[::1]:1194"
  xn--n8jaj1e5azegs1r0c8d2452g.jp:
    backends:
      -
        addr: "[::1]:8443"
  ma.fono.jp:
    backends:
      -
        addr: "[::1]:8443"
  4no.jp:
    backends:
      -
        addr: "[::1]:8443"
  emacs.tech:
    backends:
      -
        addr: "[::1]:8443"
