version: "2"
services:
    slt6:
       build: .
       volumes:
           - ${PWD}/config6.yml:/go/src/app/config.yml
       restart: always
       network_mode: "host"
    slt:
       build: .
       volumes:
           - ${PWD}/config.yml:/go/src/app/config.yml
       restart: always
       network_mode: "host"
